FROM rhel7/rhel
LABEL version="2.0" \ 
      description="This is an example container image" \ 
      creationDate="01-09-2017" 
ENV MYSQL_ROOT_PASSWORD="my_password" \
    MYSQL_DATABASE="my_database"

